-- Chạy trong SQL Editor. Bảng lưu vết mỗi mẻ pha đã "Xác nhận đã pha" (từ tab Pha chế thủ công
-- lẫn tab Chờ SX) — 1 dòng / 1 mẻ (ma_sp + pha_me), tự tạo ngay lúc xác nhận với số lượng dự kiến
-- (cỡ lô), các trường sản phẩm hoàn thiện/số lô/NSX/HSD để trống, NCV điền sau khi đóng gói xong.
create table if not exists finished_batches (
  id bigint generated by default as identity primary key,
  ma_sp text not null references products(ma_sp),
  pha_me text not null,
  so_luong_du_kien numeric,
  ten_hoan_thien text,
  so_lo text,
  nsx date,
  hsd date,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique (ma_sp, pha_me)
);

alter table finished_batches enable row level security;

create policy "finished_batches_select_approved" on finished_batches for select
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "finished_batches_insert_approved" on finished_batches for insert
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "finished_batches_update_approved" on finished_batches for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
