-- QC gửi đề nghị xuất chủng giống (chưa trừ tồn, chưa vào Nhật ký xuất/nhập) — admin duyệt
-- (sửa lại nếu cần + điền Người kiểm tra/Người phê duyệt) rồi mới ghi thật vào
-- lenmen_seed_movements. Xử lý xong thì xoá luôn dòng đề nghị, không lưu trạng thái "đã
-- duyệt" riêng. Chạy sau migration_lenmen_giong_huy_0_ong.sql, 1 lần trong Supabase
-- Dashboard > SQL Editor.

create table if not exists lenmen_seed_xuat_requests (
  id bigint generated by default as identity primary key,
  seed_lot_id bigint not null references lenmen_seed_lots(id) on delete cascade,
  so_ong integer not null check (so_ong > 0),
  ngay date not null default current_date,
  muc_dich_loai text check (muc_dich_loai in ('theo_doi_dod','nghien_cuu','san_xuat','huy')),
  lo_san_xuat text,
  nguoi_thuc_hien text,
  ghi_chu text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists lenmen_seed_xuat_requests_lot_idx
  on lenmen_seed_xuat_requests (seed_lot_id);

alter table lenmen_seed_xuat_requests enable row level security;

-- Đọc: người tạo thấy đề nghị của mình, admin thấy tất cả (để duyệt).
create policy "lenmen_seed_xuat_requests_select" on lenmen_seed_xuat_requests for select
  using (created_by = auth.uid()
    or exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin'));

-- Tạo: chỉ admin + QC (khớp đúng phân quyền mới cho nút Xuất), bắt buộc tự đứng tên.
create policy "lenmen_seed_xuat_requests_insert" on lenmen_seed_xuat_requests for insert
  with check (
    created_by = auth.uid()
    and exists (select 1 from profiles p where p.id = auth.uid() and p.role in ('admin','qc'))
  );

-- Xoá: người tạo tự rút đề nghị của mình, hoặc admin xoá sau khi đã đẩy vào lịch sử.
create policy "lenmen_seed_xuat_requests_delete" on lenmen_seed_xuat_requests for delete
  using (created_by = auth.uid()
    or exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin'));
