-- Kho chủng giống: số ống tồn, vị trí trong kho, và nhật ký xuất/nhập.
-- Chạy sau migration_lenmen_giong.sql.
--
-- Hai kho vật lý, đã có sẵn ở cột dieu_kien_luu của lenmen_seed_lots:
--   'am_20'     — kho tủ âm 20°C   (sổ hiện ghi "Âm 20C")
--   'nito_long' — kho nitơ lỏng −196°C
-- Không tách thành bảng "kho" riêng: chỉ có đúng 2 kho cố định, thêm bảng chỉ làm
-- mọi truy vấn phải join thêm một lần mà không được gì.

alter table lenmen_seed_lots
  -- Số ống còn trong kho. Sổ Excel không theo dõi cột này (chỉ ghi tình trạng bằng
  -- lời), nên lô cũ nhập vào sẽ để 0 và NCV đếm lại thực tế rồi nhập bù.
  add column if not exists so_ong integer not null default 0 check (so_ong >= 0),
  add column if not exists so_ong_ban_dau integer check (so_ong_ban_dau >= 0),
  -- Vị trí cụ thể trong kho, vd "Tủ 2 - Ngăn 3 - Hộp A", "Bình N2 số 1 - Canister 4".
  -- Để text tự do vì cách đánh vị trí giữa 2 kho khác hẳn nhau và còn đang thay đổi.
  add column if not exists vi_tri text;

/* ============================ Nhật ký xuất / nhập ============================ */

-- Mỗi lần đụng vào kho ghi 1 dòng. Đây là yêu cầu GMP: phải chứng minh được ống nào
-- ra khỏi kho lúc nào, ai lấy, để làm gì — không thể chỉ giữ con số tồn hiện tại.
create table if not exists lenmen_seed_movements (
  id bigint generated by default as identity primary key,
  seed_lot_id bigint not null references lenmen_seed_lots(id) on delete cascade,

  loai text not null check (loai in ('nhap', 'xuat', 'huy')),
  ngay date not null default current_date,
  -- Luôn ghi số DƯƠNG; loai quyết định cộng hay trừ vào tồn kho.
  so_ong integer not null check (so_ong > 0),

  -- Xuất để làm gì / nhập từ đâu, vd "Cấy chuyền lô 010526", "Sản xuất mẻ 030825BSM"
  muc_dich text,
  nguoi_thuc_hien text,
  ghi_chu text,

  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists lenmen_seed_movements_lot_idx
  on lenmen_seed_movements (seed_lot_id, ngay desc, id desc);

-- Cộng/trừ tồn kho ngay trong DB thay vì để client tự tính rồi ghi đè: hai người cùng
-- xuất một lúc mà tính ở client thì số tồn sẽ sai, còn ở đây thì tuần tự và luôn đúng.
create or replace function public.lenmen_apply_movement()
returns trigger
language plpgsql
as $$
declare
  ton_hien_tai integer;
begin
  select so_ong into ton_hien_tai from lenmen_seed_lots where id = new.seed_lot_id for update;

  if new.loai = 'nhap' then
    update lenmen_seed_lots set so_ong = so_ong + new.so_ong where id = new.seed_lot_id;
  else
    -- Chặn xuất quá số tồn ngay tại DB, không phụ thuộc giao diện có kiểm hay không.
    if ton_hien_tai < new.so_ong then
      raise exception 'Chỉ còn % ống trong kho, không thể % % ống',
        ton_hien_tai, case new.loai when 'xuat' then 'xuất' else 'huỷ' end, new.so_ong;
    end if;
    update lenmen_seed_lots set so_ong = so_ong - new.so_ong where id = new.seed_lot_id;
  end if;

  return new;
end;
$$;

drop trigger if exists lenmen_seed_movements_apply on lenmen_seed_movements;
create trigger lenmen_seed_movements_apply
  after insert on lenmen_seed_movements
  for each row execute function public.lenmen_apply_movement();

/* ==================================== RLS ==================================== */

alter table lenmen_seed_movements enable row level security;

create policy "lenmen_seed_movements_select_approved" on lenmen_seed_movements for select
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "lenmen_seed_movements_insert_approved" on lenmen_seed_movements for insert
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
-- Nhật ký chỉ ghi thêm, không sửa/xoá — nhập nhầm thì ghi một dòng ngược lại để đối trừ,
-- giữ nguyên vết. Đó là toàn bộ giá trị của một cuốn nhật ký kho.
