-- Menu "Bảo quản chủng giống" — dựng theo đúng file Excel đang dùng
-- ("File tổng SỐ LÔ", các sheet Nhãn, DOD-*/SUBTILIS/CLAUSII, và sheet Lọc/Protocol).
-- Chạy sau migration_lenmen.sql.
--
-- Mô hình gồm 2 phần, đúng như cách bộ phận đang làm việc:
--   1. lenmen_seed_lots      — sổ lô ống chủng: mỗi lô cấp giống 1 dòng, kèm KQ kiểm lúc sản xuất
--   2. lenmen_seed_stability — theo dõi độ ổn định của lô đó theo mốc tháng (0/1/3/6/9/12/18/21…)
-- Việc in nhãn không cần bảng riêng: nhãn sinh từ chính dòng lô (mã chủng, số lô, NSX, HSD,
-- nguồn gốc, người làm) đúng như các sheet "Nhãn" đang chép tay.

/* =========================== Sổ lô ống chủng giống =========================== */

create table if not exists lenmen_seed_lots (
  id bigint generated by default as identity primary key,

  -- Số lô ống chủng, vd "010526", "041025". Trùng số lô giữa 2 mã chủng khác nhau là
  -- chuyện có thật trong sổ (011122 xuất hiện ở cả PL02.3.G3 lẫn PL01.3.G4) nên khoá
  -- duy nhất phải gồm cả mã chủng.
  so_lo text not null,
  -- Mã chủng nội bộ, vd PL01.3.G4 (B.subtilis BH1), PL02.3.G3 (B.clausii G3), NC (nghiên cứu)
  ma_chung text not null,
  ten_chung text,

  -- Điều kiện lưu. Sổ hiện chỉ có "Âm 20C"; thêm sẵn nitơ lỏng cho phần sắp triển khai.
  dieu_kien_luu text check (dieu_kien_luu in ('am_20', 'nito_long')),

  ngay_san_xuat date,
  -- Hạn dùng = NSX + 1 năm theo các nhãn đang in. Vẫn để cột riêng vì có lô ghi lệch,
  -- nhập tay đè được thay vì bắt sổ phải khớp công thức.
  han_su_dung date,
  -- NSX trong sổ có ô chỉ ghi tháng ("09/2023") hoặc gõ sai ("20/25/26") — giữ nguyên
  -- bản gốc ở đây để không mất thông tin khi ngay_san_xuat không parse được.
  ngay_san_xuat_raw text,

  -- Lô/mẻ mà ống chủng này cấy chuyền ra từ đó, vd "020222BC", "2200121", "Mẻ 95", "ĐK"
  nguon_goc text,

  -- Kết quả kiểm lúc cấp giống. Để text (trừ mật độ) vì sổ ghi cả "Đạt", "80%",
  -- "Kém hơn 1-4" — ép enum sẽ làm mất sắc thái người làm cố ý ghi.
  mat_do numeric,                 -- đơn vị 10^9 CFU/ml
  nhiem_khuan text,
  do_dong_deu text,
  kha_nang_tao_bao_tu text,

  -- Diễn biến sử dụng, vd "Đang dùng để sx", "Đã sản xuất", "Chưa nhập kho, để theo dõi thêm"
  tinh_trang_sx text,
  nguoi_lam text,
  ghi_chu text,

  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (ma_chung, so_lo)
);

drop trigger if exists lenmen_seed_lots_set_updated_at on lenmen_seed_lots;
create trigger lenmen_seed_lots_set_updated_at
  before update on lenmen_seed_lots
  for each row execute function set_updated_at();

-- Hạn dùng mặc định = NSX + 1 năm, chỉ điền khi người nhập bỏ trống.
create or replace function public.lenmen_seed_lot_default_hsd()
returns trigger
language plpgsql
as $$
begin
  if new.han_su_dung is null and new.ngay_san_xuat is not null then
    new.han_su_dung := new.ngay_san_xuat + interval '1 year' - interval '1 day';
  end if;
  return new;
end;
$$;

drop trigger if exists lenmen_seed_lots_default_hsd on lenmen_seed_lots;
create trigger lenmen_seed_lots_default_hsd
  before insert or update on lenmen_seed_lots
  for each row execute function public.lenmen_seed_lot_default_hsd();

create index if not exists lenmen_seed_lots_ma_chung_idx on lenmen_seed_lots (ma_chung);
create index if not exists lenmen_seed_lots_hsd_idx on lenmen_seed_lots (han_su_dung);

/* ========================= Theo dõi độ ổn định theo mốc ========================= */

-- 1 dòng = 1 mốc thời gian của 1 lô. Đúng bố cục các sheet DOD-*/SUBTILIS/CLAUSII:
-- cột là mốc tháng, dòng là 7 chỉ tiêu — ở đây lật lại cho đúng chuẩn quan hệ, giao diện
-- vẫn dựng lại thành ma trận như cũ.
create table if not exists lenmen_seed_stability (
  id bigint generated by default as identity primary key,
  seed_lot_id bigint not null references lenmen_seed_lots(id) on delete cascade,

  -- Mốc theo dõi tính bằng tháng kể từ NSX. 0 = "Ban đầu". Sổ có cả mốc lẻ (4, 11, 15,
  -- 16, 21 tháng) do lấy mẫu thực tế lệch lịch, nên KHÔNG ràng buộc vào tập cố định.
  moc_thang smallint not null check (moc_thang >= 0),
  ngay_kiem date,

  -- Mẻ sản xuất dùng để đánh giá tại mốc này, vd "020722BS", "010223BSM"
  me text,

  -- 5 chỉ tiêu theo dõi (2 dòng đầu của sheet là Mẻ và NSX, đã nằm ở trên/ở bảng lô).
  mat_do_ong_chung numeric,     -- ngưỡng: không nhỏ hơn 10^9 CFU/ml
  do_dong_deu text,             -- xét OD NCC1
  mat_do_co_dac numeric,        -- ngưỡng: không nhỏ hơn 10^10 CFU/ml
  kha_nang_tao_bao_tu text,     -- ngưỡng: không ít hơn 70%
  gioi_han_nhiem_khuan text,    -- ngưỡng: không có tạp nhiễm

  ghi_chu text,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (seed_lot_id, moc_thang)
);

drop trigger if exists lenmen_seed_stability_set_updated_at on lenmen_seed_stability;
create trigger lenmen_seed_stability_set_updated_at
  before update on lenmen_seed_stability
  for each row execute function set_updated_at();

create index if not exists lenmen_seed_stability_lot_idx on lenmen_seed_stability (seed_lot_id, moc_thang);

/* ============================== Lịch kiểm định kỳ ============================== */

-- Sheet "Lọc" tính "chỉ tiêu cần thực hiện" từ bảng Protocol (tháng -> chỉ tiêu).
-- Đưa protocol vào lenmen_settings để admin sửa được mà không phải đụng code.
insert into lenmen_settings (key, value) values
  ('seed_stability_protocol',
   '[{"thang":1,"chi_tieu":["Định lượng"]},' ||
   '{"thang":3,"chi_tieu":["Định lượng"]},' ||
   '{"thang":6,"chi_tieu":["Định lượng","Khả năng tạo bào tử"]},' ||
   '{"thang":9,"chi_tieu":["Định lượng"]},' ||
   '{"thang":12,"chi_tieu":["Định lượng","Khả năng tạo bào tử"]}]')
on conflict (key) do nothing;

/* ==================================== RLS ==================================== */

alter table lenmen_seed_lots enable row level security;
alter table lenmen_seed_stability enable row level security;

create policy "lenmen_seed_lots_select_approved" on lenmen_seed_lots for select
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "lenmen_seed_lots_insert_approved" on lenmen_seed_lots for insert
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "lenmen_seed_lots_update_approved" on lenmen_seed_lots for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
-- Không mở delete: sổ chủng giống là hồ sơ GMP, lô bỏ dùng thì ghi vào tinh_trang_sx.

create policy "lenmen_seed_stability_select_approved" on lenmen_seed_stability for select
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "lenmen_seed_stability_insert_approved" on lenmen_seed_stability for insert
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "lenmen_seed_stability_update_approved" on lenmen_seed_stability for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
