-- Chạy trong SQL Editor. Bảng lưu đánh giá AI hàng tháng về xu hướng nhiễm khuẩn NL (tab "Xu hướng
-- NL" trong Quản lý NL) — 1 dòng / 1 tháng, NCV tự bấm "Tạo đánh giá AI" khi cần (không tự động).
create table if not exists nl_trend_reports (
  id bigint generated by default as identity primary key,
  report_month date not null, -- luôn là ngày 1 của tháng, vd 2026-07-01
  stats jsonb not null,
  ai_assessment text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique (report_month)
);

alter table nl_trend_reports enable row level security;

create policy "nl_trend_reports_select_approved" on nl_trend_reports for select
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "nl_trend_reports_insert_approved" on nl_trend_reports for insert
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "nl_trend_reports_update_approved" on nl_trend_reports for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
