-- Chạy trong SQL Editor sau các migration trước đó. Bổ sung:
--  1) sản phẩm 2 thành phần hoạt chất (pool2/ham_luong2, để trống = SP 1 thành phần)
--  2) bảng mix_plans lưu kế hoạch mẻ pha do thuật toán (src/lib/mixPlanner.js) tính ra,
--     cùng quyết định duyệt của NCV (audit trail: ai duyệt, lúc nào).
-- Đây chỉ là màn hình XEM TRƯỚC + DUYỆT — không tự động đánh dấu "Đã pha" cho NL,
-- việc đó vẫn thao tác tay ở tab "Pha" như trước.

alter table products add column if not exists pool2 text
  check (pool2 in ('subtilis', 'clausii-loai1', 'clausii-loai2'));
alter table products add column if not exists ham_luong2 numeric;

create table if not exists mix_plans (
  id bigint generated by default as identity primary key,
  ma_sp text not null references products(ma_sp),
  so_ong_muc_tieu numeric not null,
  ket_qua jsonb not null,
  trang_thai text not null default 'cho_duyet'
    check (trang_thai in ('cho_duyet', 'duyet', 'khong_duyet', 'dieu_chinh')),
  ghi_chu text,
  created_by uuid references auth.users(id),
  decided_by uuid references auth.users(id),
  decided_at timestamptz,
  created_at timestamptz not null default now()
);

alter table mix_plans enable row level security;

create policy "mix_plans_select_approved" on mix_plans for select
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "mix_plans_insert_approved" on mix_plans for insert
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "mix_plans_update_approved" on mix_plans for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
