-- Gộp "Hệ thống cảnh báo lên men" (app Node + SQLite chạy riêng ở
-- canhbaolenmen.dtpduyetquytrinhsanxuat.io.vn) vào đây thành 1 menu, ngay dưới "Sản phẩm".
-- Chạy 1 lần trong Supabase Dashboard > SQL Editor, SAU schema.sql.
--
-- Đặt tiền tố lenmen_ cho cả 3 bảng: dữ liệu lên men là công đoạn TRƯỚC nguyên liệu
-- (thu bào tử → NL), không trộn lẫn với materials/products vốn nói về khâu pha chế.
--
-- Ánh xạ vai trò — app cũ có 4 vai trò riêng, đây quy về bộ vai trò sẵn có của profiles:
--   admin  -> admin   (toàn quyền)
--   qc     -> qc      (sửa Danh sách lô: kết quả nhiễm khuẩn + định lượng)
--   khsx   -> kh      (sửa Kế hoạch sản xuất)
--   viewer -> ktv     (chỉ xem)
-- Giống materials/products: RLS chỉ chặn ở mức "đã đăng nhập và được duyệt", còn phân
-- quyền theo vai trò thì UI lo (xem applyRolePermissionsToUI trong app cũ). Giữ đúng
-- quy ước đang dùng để không sinh ra 2 mô hình phân quyền khác nhau trong cùng 1 app.

/* ============================ Danh sách lô lên men ============================ */

create table if not exists lenmen_batches (
  id bigint generated by default as identity primary key,
  raw_material text,
  -- Mã lô: khoá nghiệp vụ, Apps Script/nhập liệu đều upsert theo cột này
  lot_number text not null,
  production_batch text,
  factory text,
  scale text,
  finished_tubes bigint,
  -- Chuỗi kết quả QC dạng "Vị trí: kết quả; Vị trí: kết quả..." (giữ nguyên để tra cứu/lịch sử)
  qc_result text,
  is_infected boolean not null default false,
  contaminant text,
  notes text,
  -- {"ok": ["Ống chủng", ...], "fail": [...]} — nguồn thật của kết luận QC; qc_result ở trên
  -- là dạng chuỗi sinh ra từ đây, giữ lại cho các lô cũ nhập trước khi có ô tích theo vị trí.
  qc_details jsonb,
  -- Lô tạo từ Kế hoạch sản xuất bắt đầu ở 'Chờ lên men'; khi QC lưu kết quả thật thì tự
  -- chuyển sang 'Chờ pha' (đạt) hoặc 'Chờ hủy' (nhiễm) — xem trigger bên dưới.
  prep_status text check (prep_status in ('Chờ lên men', 'Chờ pha', 'Chờ hủy', 'Đã xử lý')),
  -- [{"volume","density_before","density_after","ph"}, ...] — 1 phần tử / 1 chai lấy mẫu
  density_details jsonb,
  concentrate_system text,
  final_concentrate_status text,
  final_concentrate_detail text,
  planned_time text,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (lot_number)
);

-- Dùng lại set_updated_at() đã khai báo trong schema.sql
drop trigger if exists lenmen_batches_set_updated_at on lenmen_batches;
create trigger lenmen_batches_set_updated_at
  before update on lenmen_batches
  for each row execute function set_updated_at();

-- Tự chuyển trạng thái khi QC nhập kết quả cho lô đang "Chờ lên men".
-- App cũ làm việc này trong handler POST /api/batch; đưa xuống DB để mọi đường ghi
-- (web, Apps Script, script nhập liệu) đều tuân thủ như nhau, không phải nhớ lặp lại.
create or replace function public.lenmen_auto_prep_status()
returns trigger
language plpgsql
as $$
begin
  if old.prep_status = 'Chờ lên men'
     and new.prep_status is not distinct from old.prep_status
     and new.is_infected is distinct from old.is_infected then
    new.prep_status := case when new.is_infected then 'Chờ hủy' else 'Chờ pha' end;
  end if;
  return new;
end;
$$;

drop trigger if exists lenmen_batches_auto_prep_status on lenmen_batches;
create trigger lenmen_batches_auto_prep_status
  before update on lenmen_batches
  for each row execute function public.lenmen_auto_prep_status();

create index if not exists lenmen_batches_production_batch_idx on lenmen_batches (production_batch);
create index if not exists lenmen_batches_prep_status_idx on lenmen_batches (prep_status);

/* ========================== Kế hoạch sản xuất theo tuần ========================== */

create table if not exists lenmen_khsx_plans (
  id bigint generated by default as identity primary key,
  -- Ngày thứ Hai của tuần (yyyy-mm-dd)
  week_start date not null,
  -- Dòng hệ: 'he-pha-1000l' | 'he-len-men' | 'linh-can-nl' (app cũ dùng KHSX_ROW_KEYS)
  row_key text not null,
  -- 0 = thứ Hai ... 6 = Chủ nhật
  day_index smallint not null check (day_index between 0 and 6),
  cell_type text not null check (cell_type in ('fermentation', 'free_text')),
  free_text text,
  lot_number text,
  -- Nhập Mã lô là hành động DUY NHẤT tạo/liên kết sang Danh sách lô; mọi thứ khác trong ô
  -- chỉ là ghi chú tự do, QC điền các trường có cấu trúc sau.
  linked_batch_id bigint references lenmen_batches(id) on delete set null,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  unique (week_start, row_key, day_index)
);

drop trigger if exists lenmen_khsx_plans_set_updated_at on lenmen_khsx_plans;
create trigger lenmen_khsx_plans_set_updated_at
  before update on lenmen_khsx_plans
  for each row execute function set_updated_at();

/* ================================ Cài đặt đặc thù ================================ */

-- Chỉ giữ phần cài đặt KHÔNG trùng với trang lớn. Quản lý tài khoản/phân quyền đã có ở
-- tab "Người dùng" + "Tài khoản của tôi" của qlsp nên bỏ hẳn admin.html; settings.html
-- cũng bỏ, phần còn lại (mốc định lượng, công thức tính ống, lịch gửi mail) về bảng này.
create table if not exists lenmen_settings (
  key text primary key,
  value text,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);

drop trigger if exists lenmen_settings_set_updated_at on lenmen_settings;
create trigger lenmen_settings_set_updated_at
  before update on lenmen_settings
  for each row execute function set_updated_at();

-- Giá trị đang chạy trên hệ thống cũ (tháng 8/2026). Sau khi nhập xong dữ liệu thật thì
-- chỉnh lại trong giao diện, không sửa file này.
insert into lenmen_settings (key, value) values
  -- Định lượng mật độ chỉ áp dụng từ mốc này trở đi; lô cũ hơn đã "Đã xử lý", để yên.
  ('density_cutoff_month', '5'),
  ('density_cutoff_year', '2026'),
  -- Số chai lấy mẫu cho lô 1000L, các cỡ lô khác quy đổi theo tỉ lệ (tối thiểu 1)
  ('density_chai_per_1000l', '5'),
  ('density_unit_volume', 'L'),
  ('density_unit_density', '10^8 CFU/ml'),
  -- Số ống thành phẩm = (mật độ sau heat × thể tích × hệ số nhân) ÷ d1 ÷ d2
  ('density_formula_bh1_mult', '1000'),
  ('density_formula_bh1_d1', '5.2'),
  ('density_formula_bh1_d2', '4.5'),
  ('density_formula_g3_mult', '1000'),
  ('density_formula_g3_d1', '5.2'),
  ('density_formula_g3_d2', '4.5'),
  -- Lịch gửi mail: Apps Script đọc các key này (thay cho scheduler.js của app cũ).
  -- *_day theo chuẩn getDay() của JS: 0 = Chủ nhật ... 6 = thứ Bảy.
  ('reminder_email', ''),
  ('reminder_day', '4'),
  ('reminder_hour', '15'),
  ('reminder_last_sent', ''),
  ('weekly_emails', ''),
  ('weekly_day', '6'),
  ('weekly_hour', '10'),
  ('weekly_last_sent', ''),
  ('monthly_emails', ''),
  ('monthly_day', '3'),
  ('monthly_hour', '9'),
  ('monthly_last_sent', ''),
  ('khsx_emails', '')
on conflict (key) do nothing;

/* ==================================== RLS ==================================== */

alter table lenmen_batches enable row level security;
alter table lenmen_khsx_plans enable row level security;
alter table lenmen_settings enable row level security;

create policy "lenmen_batches_select_approved" on lenmen_batches for select
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "lenmen_batches_insert_approved" on lenmen_batches for insert
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "lenmen_batches_update_approved" on lenmen_batches for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "lenmen_batches_delete_approved" on lenmen_batches for delete
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));

create policy "lenmen_khsx_plans_select_approved" on lenmen_khsx_plans for select
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "lenmen_khsx_plans_insert_approved" on lenmen_khsx_plans for insert
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "lenmen_khsx_plans_update_approved" on lenmen_khsx_plans for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "lenmen_khsx_plans_delete_approved" on lenmen_khsx_plans for delete
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));

-- Cài đặt: ai đã duyệt cũng đọc được (giao diện cần mốc định lượng + công thức để tính
-- số ống ngay trên trình duyệt), nhưng chỉ admin mới ghi.
create policy "lenmen_settings_select_approved" on lenmen_settings for select
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "lenmen_settings_write_admin" on lenmen_settings for all
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin'));

-- Nhiều QC cùng nhập kết quả một lúc — bật realtime như materials để không ghi đè nhau.
alter publication supabase_realtime add table lenmen_batches;
