-- Chạy toàn bộ file này trong Supabase Dashboard > SQL Editor (1 lần khi khởi tạo project)

create table if not exists materials (
  id bigint generated by default as identity primary key,
  strain text not null check (strain in ('subtilis', 'clausii')),
  stt text,
  ten_nl text,
  chung text,
  dot_san_xuat text,
  -- Ngày thu dịch bào tử (khác dot_san_xuat = ngày sản xuất môi trường), tự động điền
  -- từ mail "Thu bào tử" khi có, hoặc để trống nếu nhập tay không điền.
  thoi_gian_thu date,
  so_lo text not null,
  lo text,
  chai text,
  lo_chung text,
  v_dich numeric,
  cam_quan text,
  ph numeric,
  md_nhan numeric,
  md_sh numeric,
  ty_le_bao_tu numeric,
  nhiem_khuan text,
  nhiem_con_nao text,
  tinh_trang_src text,
  ghi_chu text,
  me_che text,
  da_pha boolean not null default false,
  -- Lúc chai chuyển sang "Đã pha" (bấm "Xác nhận đã pha" hoặc tự động sau 30 ngày Chờ SX) — để NCV
  -- xem lại đúng thời điểm, khác với created_at (lúc nhập lô) và updated_at (mọi lần sửa khác).
  da_pha_at timestamptz,
  pha_product text,
  pha_me text,
  loai smallint,
  last_alert_month smallint,
  ph_invalid boolean not null default false,
  -- Đã gửi cảnh báo "quá 15 ngày chưa nhập kết quả QC" cho chai này chưa —
  -- tránh gửi lặp lại mỗi ngày.
  qc_alert_sent boolean not null default false,
  pending_delete boolean not null default false,
  deleted_at timestamptz,
  -- "Chờ SX": đã lên lệnh sản xuất từ 1 kế hoạch mẻ pha đã DUYỆT — không còn tính vào kế hoạch pha
  -- chế nào khác nữa (xem migration_cho_sx.sql). cho_sx_at dùng để tự động chuyển "Đã pha" sau 30
  -- ngày nếu quên xác nhận tay; mix_plan_id/mix_plan_me_so đánh dấu đúng mẻ nào của kế hoạch nào.
  cho_sx boolean not null default false,
  cho_sx_at timestamptz,
  mix_plan_id bigint,
  mix_plan_me_so integer,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (so_lo)
);

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  phone text,
  full_name text,
  department text,
  employee_code text,
  role text not null default 'qc' check (role in ('admin', 'rd', 'qa', 'qc', 'kh', 'ktv')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

create table if not exists products (
  ma_sp text primary key,
  ten_sp text,
  pool text not null check (pool in ('subtilis', 'clausii-loai1', 'clausii-loai2')),
  thanh_phan text,
  ham_luong numeric,
  tube_ml numeric,
  so_ong_nhip numeric,
  ncv text,
  -- SP 2 thành phần hoạt chất (vd Co-biozin): pool2/ham_luong2 là chủng + mật độ
  -- đích của thành phần thứ 2, pha CHUNG 1 tank với thành phần chính (pool/ham_luong).
  -- Để trống (null) = SP chỉ có 1 thành phần.
  pool2 text check (pool2 in ('subtilis', 'clausii-loai1', 'clausii-loai2')),
  ham_luong2 numeric,
  thanh_phan2 text,
  -- Chấp nhận dùng loại NL còn lại làm dự phòng khi loại chính (pool/pool2) không đủ, vd
  -- Progermila ưu tiên loại 1 nhưng vẫn dùng được loại 2; Co-biozin ưu tiên loại 2 nhưng vẫn
  -- dùng được loại 1. Mặc định false = chỉ dùng đúng loại đã khai báo.
  allow_other_loai boolean not null default false,
  -- Thứ tự hiển thị tuỳ chỉnh (admin kéo thả trong tab Sản phẩm); null = xếp theo ma_sp.
  sort_order integer
);

create table if not exists mix_plans (
  id bigint generated by default as identity primary key,
  ma_sp text not null references products(ma_sp),
  so_ong_muc_tieu numeric not null,
  ket_qua jsonb not null,
  trang_thai text not null default 'cho_duyet'
    check (trang_thai in ('cho_duyet', 'duyet', 'khong_duyet', 'dieu_chinh')),
  ghi_chu text,
  created_by uuid references auth.users(id),
  decided_by uuid references auth.users(id),
  decided_at timestamptz,
  created_at timestamptz not null default now(),
  -- Trỏ sang dòng MỚI khi dòng "Cần điều chỉnh" này đã được sửa lại (xem migration_mix_plans_supersede.sql)
  -- — dòng gốc vẫn giữ nguyên làm lưu vết, KHÔNG bị xoá/ghi đè.
  superseded_by_id bigint references mix_plans(id)
);

-- 1 dòng / 1 mẻ đã "Xác nhận đã pha" (ma_sp + pha_me) — tự tạo ngay lúc xác nhận với số lượng dự
-- kiến (cỡ lô); sản phẩm hoàn thiện/số lô/NSX/HSD để trống, NCV điền sau khi đóng gói xong (xem
-- tab Sản phẩm > Lịch sử pha chế).
create table if not exists finished_batches (
  id bigint generated by default as identity primary key,
  ma_sp text not null references products(ma_sp),
  pha_me text not null,
  so_luong_du_kien numeric,
  ten_hoan_thien text,
  so_lo text,
  nsx date,
  hsd date,
  -- Xử lý NL đầu vào, xử lý BTP sau pha (trong tank), xử lý BTP sau khi đóng ống, và quy trình xử
  -- lý khác nếu có — mỗi SP có quy trình riêng (có SP hấp sau đóng ống, có SP hấp/duy trì nhiệt
  -- ngay trong tank), NCV điền tay theo đúng quy trình của mẻ đó.
  xu_ly_nguyen_lieu_dau_vao text,
  xu_ly_btp_sau_pha text,
  xu_ly_sau_dong_ong text,
  quy_trinh_khac text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique (ma_sp, pha_me)
);

-- Đánh giá AI hàng tháng về xu hướng nhiễm khuẩn NL (tab "Xu hướng NL" trong Quản lý NL) — 1 dòng /
-- 1 tháng, NCV tự bấm "Tạo đánh giá AI" khi cần (không tự động chạy).
create table if not exists nl_trend_reports (
  id bigint generated by default as identity primary key,
  report_month date not null,
  stats jsonb not null,
  ai_assessment text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique (report_month)
);

-- materials.mix_plan_id không đặt FK ngay tại create table materials ở trên vì mix_plans được tạo
-- SAU trong file này (thứ tự chạy top-to-bottom) — thêm ràng buộc ở đây, sau khi mix_plans đã tồn tại.
alter table materials add constraint materials_mix_plan_id_fkey
  foreign key (mix_plan_id) references mix_plans(id) on delete set null;

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists materials_set_updated_at on materials;
create trigger materials_set_updated_at
  before update on materials
  for each row execute function set_updated_at();

insert into products (ma_sp, ten_sp, pool, thanh_phan, ham_luong, tube_ml, so_ong_nhip, ncv) values
  ('DOMUVAR', 'Domuvar', 'subtilis', 'B. subtilis', 4e8, 5.2, 120000, ''),
  ('PROGERMILA', 'Progermila', 'clausii-loai1', 'B. clausii', 4e8, 5, 100000, ''),
  ('CO-BIOZIN', 'Co-biozin', 'clausii-loai2', 'B. clausii + B. subtilis', 4e8, 5, 100000, '')
on conflict (ma_sp) do nothing;

alter table materials enable row level security;
alter table products enable row level security;
alter table profiles enable row level security;
alter table mix_plans enable row level security;
alter table finished_batches enable row level security;
alter table nl_trend_reports enable row level security;

-- Tự tạo dòng profiles khi có user mới trong auth.users (đăng ký qua form hoặc
-- admin tạo tay trong Dashboard đều kích hoạt). security definer để bỏ qua RLS
-- của chính bảng profiles khi insert.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, department, employee_code, role)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'department',
    new.raw_user_meta_data ->> 'employee_code',
    case upper(new.raw_user_meta_data ->> 'department')
      when 'RD' then 'rd'
      when 'QA' then 'qa'
      when 'QC' then 'qc'
      when 'KH' then 'kh'
      else 'qc'
    end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create policy "profiles_select_auth" on profiles for select
  using (auth.role() = 'authenticated');
create policy "profiles_update_admin" on profiles for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (true);

-- Cho user tự cập nhật CỘT EMAIL hiển thị (profiles.email) của CHÍNH MÌNH qua 1 hàm RPC hẹp —
-- không mở rộng policy update trực tiếp trên bảng để tránh user tự nâng quyền role/status.
create or replace function public.update_own_profile_email(new_email text)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  update public.profiles set email = new_email where id = auth.uid();
end;
$$;
grant execute on function public.update_own_profile_email(text) to authenticated;

-- VIEW admin xem nhanh trong Table Editor (schema public, không cần đổi sang schema "auth")
-- gồm cả password đã băm — REVOKE khỏi anon/authenticated để không lộ qua REST API công khai.
create or replace view public.user_accounts_admin_view as
select
  p.id, p.full_name, p.phone, p.email, u.encrypted_password,
  p.role, p.status, p.department, p.employee_code, p.created_at
from public.profiles p
join auth.users u on u.id = p.id;
revoke all on public.user_accounts_admin_view from anon, authenticated;

-- Chỉ tài khoản đã đăng nhập VÀ được admin duyệt (profiles.status = 'approved')
-- mới đọc/ghi materials, products. Google Apps Script dùng service_role key nên
-- luôn bỏ qua RLS, không bị ảnh hưởng bởi các policy này.
create policy "materials_select_approved" on materials for select
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "materials_insert_approved" on materials for insert
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "materials_update_approved" on materials for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "materials_delete_approved" on materials for delete
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));

create policy "products_select_approved" on products for select
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "products_insert_approved" on products for insert
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "products_update_approved" on products for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));

create policy "mix_plans_select_approved" on mix_plans for select
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "mix_plans_insert_approved" on mix_plans for insert
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "mix_plans_update_approved" on mix_plans for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "mix_plans_delete_approved" on mix_plans for delete
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));

create policy "finished_batches_select_approved" on finished_batches for select
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "finished_batches_insert_approved" on finished_batches for insert
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "finished_batches_update_approved" on finished_batches for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));

create policy "nl_trend_reports_select_approved" on nl_trend_reports for select
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "nl_trend_reports_insert_approved" on nl_trend_reports for insert
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));
create policy "nl_trend_reports_update_approved" on nl_trend_reports for update
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.status = 'approved'));

alter publication supabase_realtime add table materials;

-- QUAN TRỌNG: chạy dòng dưới đây MỘT LẦN sau khi cài đặt, thay email admin thật,
-- để có admin đầu tiên duyệt được người khác qua giao diện.
-- update profiles set role = 'admin', status = 'approved' where email = 'ban@vidu.com';
